name: Continuous Integration and Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go-task  
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup Vtiger
        run: |
          cp .env.example .env

      - name: Composer Lint
        run: php phplint.phar

      - name: Composer Validate
        run: composer validate --no-check-all --strict

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      VTIGER_PATH: '/var/www/vtiger/vtigercrm'
      WWW_USER: 'www-data'
      WWW_HOME: '/var/www'

    steps:
      - name: Run deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          scippt: |
            sudo cp -r /home/${{ secrets.USER }}/.ssh ${{ env.WWW_HOME }}/
            sudo chown -R ${{ env.WWW_USER }}: ${{ env.WWW_HOME }}/.ssh
            cd ${{ env.VTIGER_PATH }}

            echo -e  "\033[0;32m git pull \033[0m "
            if ! sudo -u ${WWW_USER} git pull origin main; then
              sudo -u ${WWW_USER} git fetch origin main
              sudo -u ${WWW_USER} git reset --hard origin/main
            else
              echo "Pull successful, no conflicts"
            fi            

            echo "\033[0;32m run deploy command \033[0m"
            sudo -u ${WWW_USER} sudo task deploy

            echo "\033[0;32m run migrate command \033[0m"
            sudo -u ${WWW_USER} task migratea

            echo -e "\033[0;32m remove \033[0m"
            sudo rm -rf ${{ env.WWW_HOME }}/.ssh
